name: Final Image Builds

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      latest:
        required: true
        type: string
      variant:
        required: true
        type: string
      os:
        required: true
        type: string
      base_image_registry:
        required: false
        type: string
        default: 'public.ecr.aws'

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      packages: write
      actions: write
      contents: read
      pull-requests: write
      id-token: write
      attestations: write
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup variants
        id: compute_variants
        run: |
          echo "variant_os=${{ inputs.variant }}${{ inputs.os != 'debian' && format('-{0}', inputs.os) || '' }}" >> $GITHUB_OUTPUT
          echo "base_variant=${{ inputs.variant == 'zts' && format('{0}', inputs.variant) || 'cli' }}" >> $GITHUB_OUTPUT
          echo "base_variant_os=${{ inputs.variant == 'zts' && format('{0}', inputs.variant) || 'cli' }}${{ inputs.os != 'debian' && format('-{0}', inputs.os) || '' }}" >> $GITHUB_OUTPUT
      - name: Setup base image path
        id: image_path
        run: |
          if [ "${{ inputs.base_image_registry }}" = "public.ecr.aws" ]; then
            echo "path=docker/library" >> $GITHUB_OUTPUT
          else
            echo "path=library" >> $GITHUB_OUTPUT
          fi
      - name: Set semver tags
        id: semver
        run: |
          VERSION="${{ inputs.version }}"  # passed to your reusable workflow
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/php
            docker.io/${{ github.repository_owner }}/php
          tags: |
            type=raw,value=${{ steps.compute_variants.outputs.variant_os }},prefix=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch || 0 }}-
            type=raw,value=${{ steps.compute_variants.outputs.variant_os }},prefix=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}-
            type=raw,value=${{ steps.compute_variants.outputs.variant_os }},prefix=${{ steps.semver.outputs.major }}-,enable=${{ inputs.version == inputs.latest }}
            type=raw,value=${{ steps.compute_variants.outputs.variant_os }},enable=${{ inputs.version == inputs.latest }}
            type=raw,value=latest,enable=${{ inputs.version == inputs.latest && steps.compute_variants.outputs.variant_os == 'cli'}}
          labels: |
            org.opencontainers.image.title=PHP${{ inputs.version }} ${{ steps.compute_variants.outputs.variant_os }}
            org.opencontainers.image.description=PHP${{ inputs.version }} ${{ steps.compute_variants.outputs.variant_os }} preinstalled with various extensions
            org.opencontainers.image.vendor=MDP Software Development Services
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/blob/${{ github.head_ref || github.ref_name }}/builder/${{ inputs.os }}/Dockerfile-image
            org.opencontainers.image.version=${{ inputs.version }}-${{ steps.compute_variants.outputs.variant_os }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.base.name=docker.io/library/php:${{ inputs.version }}-${{ steps.compute_variants.outputs.variant_os }}
            org.opencontainers.image.licenses=GNU GPLv3
            org.opencontainers.image.authors=Melvin D. Protacio <mdprotacio@outlook.com>
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build PHP ${{ inputs.version }} ${{ steps.compute_variants.outputs.variant_os }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: builder/${{ inputs.os }}/Dockerfile-image
          build-args: |
            PHP_VERSION=${{ inputs.version }}
            PHP_VARIANT=${{ inputs.variant }}
            PHP_BASE_VARIANT=${{ steps.compute_variants.outputs.base_variant }}
            BASE_IMAGE_REGISTRY=${{ inputs.base_image_registry }}
            BASE_IMAGE_PATH=${{ steps.image_path.outputs.path }}
          target: ${{ inputs.variant }}
          build-contexts: |
            php-${{ inputs.version }}-${{ steps.compute_variants.outputs.base_variant_os }}=docker-image://ghcr.io/${{ github.repository_owner }}/cache/php:${{ inputs.version }}-${{ steps.compute_variants.outputs.base_variant_os }}-prebuild
          pull: ${{ github.event_name == 'pull_request' }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          sbom: true
          # Push only when running on main or master branch (for push, workflow_dispatch, or workflow_call events)
          push: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
      - name: Publish attestation
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'pull_request' }}
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/php
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
      - name: Publish attestation
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'pull_request' }}
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: docker.io/${{ github.repository_owner }}/php
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true